# Generated by Django 5.2 on 2025-04-15 10:15

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oaccount', models.CharField(default=main.models.Ogenerate_number, max_length=9, unique=True)),
                ('Oname', models.CharField(max_length=15, verbose_name='Name')),
                ('Osecondname', models.CharField(max_length=25, verbose_name='SecondName')),
                ('Ostate', models.CharField(max_length=25, verbose_name='Country')),
                ('Ophone_number', models.CharField(max_length=10, verbose_name='Number')),
                ('Obirth', models.DateField(verbose_name='Birth')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tvalue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('Tdate', models.DateTimeField(verbose_name='Date')),
                ('Tnumber', models.CharField(default=main.models.Tgenerate_number, max_length=12, unique=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transaction', to='main.owner')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transaction', to='main.owner')),
            ],
        ),
    ]
