# Generated by Django 5.2 on 2025-04-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='Obirth',
            new_name='Birth',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='Ophone_number',
            new_name='Number',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='Osecondname',
            new_name='SecondName',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='Ostate',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='Oaccount',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='Oname',
            new_name='name',
        ),
    ]
