# Generated by Django 5.2 on 2025-04-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_obirth_owner_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='name',
            new_name='Name',
        ),
    ]
