# Generated by Django 5.2 on 2025-05-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_name_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
